version: 'build-{build}'

image:
  - Visual Studio 2017
  - Ubuntu1804

environment:
  matrix:
    - TARGET: Server

install:
  - sh: sudo dpkg --add-architecture i386
  - sh: sudo apt-get update > /dev/null
  - sh: sudo apt-get install -y libc6:i386 cmake gcc g++ gcc-multilib g++-multilib patchelf ninja-build > /dev/null
  - sh: git submodule update --init --recursive
  
  - ps: |
      if ([System.Environment]::OSVersion.Platform -eq "Win32NT")
      {
        Install-Module VSSetup -Scope CurrentUser;
      }
  - cmd: git submodule update --init --recursive

build_script:
  - ps: ./scripts/BuildRelease.ps1 -Target $env:TARGET -MakeZip -CMakeArgs "-DBHL_VERSION_METADATA=`"appveyor.${env:APPVEYOR_REPO_BRANCH}.${env:APPVEYOR_BUILD_NUMBER}`""

artifacts:
  - path: autobuild/BugfixedHL-*.zip
